// ---- Cypher: create Method nodes + CALLS edges among project's own functions ----
MERGE (:Method {name: "auth.py::verify_password"});
MERGE (:Method {name: "crud.py::create_user"});
MERGE (:Method {name: "crud.py::get_tasks"});
MERGE (:Method {name: "main.py::create_task"});
MERGE (:Method {name: "main.py::delete_task"});
MERGE (:Method {name: "main.py::login"});
MERGE (:Method {name: "main.py::read_task"});
MERGE (:Method {name: "main.py::read_tasks"});
MERGE (:Method {name: "main.py::register"});
MERGE (:Method {name: "main.py::update_task"});
MERGE (:Method {name: "auth.py::hash_password"});
MERGE (:Method {name: "crud.py::_escape_like"});
MERGE (:Method {name: "crud.py::create_task"});
MERGE (:Method {name: "crud.py::get_task"});
MERGE (:Method {name: "crud.py::delete_task"});
MERGE (:Method {name: "crud.py::get_user_by_username"});
MERGE (:Method {name: "auth.py::create_access_token"});
MERGE (:Method {name: "crud.py::update_task"});
MATCH (a:Method {name: "auth.py::verify_password"}), (b:Method {name: "auth.py::hash_password"}) CREATE (a)-[:CALLS {line: 31}]->(b);
MATCH (a:Method {name: "crud.py::create_user"}), (b:Method {name: "auth.py::hash_password"}) CREATE (a)-[:CALLS {line: 12}]->(b);
MATCH (a:Method {name: "crud.py::get_tasks"}), (b:Method {name: "crud.py::_escape_like"}) CREATE (a)-[:CALLS {line: 34}]->(b);
MATCH (a:Method {name: "main.py::create_task"}), (b:Method {name: "crud.py::create_task"}) CREATE (a)-[:CALLS {line: 95}]->(b);
MATCH (a:Method {name: "main.py::delete_task"}), (b:Method {name: "crud.py::get_task"}) CREATE (a)-[:CALLS {line: 120}]->(b);
MATCH (a:Method {name: "main.py::delete_task"}), (b:Method {name: "crud.py::delete_task"}) CREATE (a)-[:CALLS {line: 124}]->(b);
MATCH (a:Method {name: "main.py::login"}), (b:Method {name: "crud.py::get_user_by_username"}) CREATE (a)-[:CALLS {line: 50}]->(b);
MATCH (a:Method {name: "main.py::login"}), (b:Method {name: "auth.py::verify_password"}) CREATE (a)-[:CALLS {line: 51}]->(b);
MATCH (a:Method {name: "main.py::login"}), (b:Method {name: "auth.py::create_access_token"}) CREATE (a)-[:CALLS {line: 57}]->(b);
MATCH (a:Method {name: "main.py::read_task"}), (b:Method {name: "crud.py::get_task"}) CREATE (a)-[:CALLS {line: 83}]->(b);
MATCH (a:Method {name: "main.py::read_tasks"}), (b:Method {name: "crud.py::get_tasks"}) CREATE (a)-[:CALLS {line: 74}]->(b);
MATCH (a:Method {name: "main.py::register"}), (b:Method {name: "crud.py::get_user_by_username"}) CREATE (a)-[:CALLS {line: 40}]->(b);
MATCH (a:Method {name: "main.py::register"}), (b:Method {name: "crud.py::create_user"}) CREATE (a)-[:CALLS {line: 46}]->(b);
MATCH (a:Method {name: "main.py::update_task"}), (b:Method {name: "crud.py::get_task"}) CREATE (a)-[:CALLS {line: 107}]->(b);
MATCH (a:Method {name: "main.py::update_task"}), (b:Method {name: "crud.py::update_task"}) CREATE (a)-[:CALLS {line: 111}]->(b);
